name: Release Gateway

on:
  push:
    branches:
      - main
    paths:
      - 'services/gateway/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        working-directory: services/gateway

      - name: Run tests
        run: bun test
        working-directory: services/gateway

      - name: Build project
        run: bun run build
        working-directory: services/gateway

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'services/gateway'